### ISSUE TITLE
版本库不对导致一些问题

### ISSUE THREAD

**Issue by brz-hub** [lturing/ORB_SLAM3_modified#1]
请问你用的是哪个版本的ubuntu以及pcl、pangolin库啊。我在自己18.4虚拟机上跑的时候，发现自己安装的pangolin库找不到geomotry、CloudPoint.cc里    
globalMap = std::make_shared<pcl::PointCloud<PointT>>();
说没有符合的构造函数。

**Comment by lturing** [comment]
https://github.com/lturing/ORB_SLAM3_modified/blob/main/CMakeLists.txt
