### ISSUE TITLE
做IMU噪声评估的时候，报错

### ISSUE THREAD

**Issue by RaySaii** [lturing/ORB_SLAM3_modified#3]
![image](https://user-images.githubusercontent.com/24506255/233816344-5146c5b8-0ace-4df7-8762-06cbbcc97979.png)
换了Allan_variance_ros提供的测试bag，也是这样，能给一下可能的出错的地方的提示吗

**Comment by lturing** [comment]
rosrun allan_variance_ros allan_variance /data/Desktop/slam/test /data/allan_variance_ros/config/sim.yaml 
你的命令中
* /data/Desktop/slam/test 换成 /data/Desktop/slam/test/allan_variance_2021-10-12-10-01-42_cooked.bag 
* /data/allan_variance_ros/config/sim.yaml 换成  /data/Desktop/slam/test/

报错提示你的数据有问题(unable to parse any message)
