### ISSUE TITLE
三维语义重建复现无效果

### ISSUE THREAD

**Issue by create-li** [lturing/ORB_SLAM3_modified#4]
readme中描述，三维语义重建只有黑屏，但没有效果。在录制视频和惯导的例子中可以看到点云等效果。

img_data 是 通过`python script/data2orbslam.py --data_dir $data` 获取的关键帧图片，。

# 三维重建(orbslam3位姿+三角化)效果
![2023-08-03 17-11-14 的屏幕截图](https://github.com/lturing/ORB_SLAM3_modified/assets/9958979/52cecedd-9200-4996-a735-78f9ad8cf3a6)

# 三维重建(orbslam3位姿+单目预测)
![2023-08-03 17-13-51 的屏幕截图](https://github.com/lturing/ORB_SLAM3_modified/assets/9958979/8651ed63-e64b-427d-aa59-f2a456d69f56)

请问大佬是什么原因？

**Comment by create-li** [comment]
# 三维重建(orbslam3位姿+单目预测)
运行打印的。

setting path: ./Examples/Monocular/mi.yaml
image directory: /media/lyq/disk/video/803/data/img
depth directory: ./depthdir
keyFrameFile directory: ./Examples/Monocular/KeyFrameTrajectory_mi.txt
Loading settings from ./Examples/Monocular/mi.yaml
Camera1.k3 optional parameter does not exist...
        -Loaded camera 1
        -Loaded image info
        -Loaded ORB settings
Viewer.imageViewScale optional parameter does not exist...
        -Loaded viewer settings
System.LoadAtlasFromFile optional parameter does not exist...
System.SaveAtlasToFile optional parameter does not exist...
        -Loaded Atlas settings
System.thFarPoints optional parameter does not exist...
        -Loaded misc parameters
----------------------------------
SLAM settings: 
        -Camera 1 parameters (Pinhole): [ 595.718 594.982 295.232 404.435 ]
        -Camera 1 distortion parameters: [  0.0659297 -0.1201 0.00345119 -0.0023523 ]
        -Original image size: [ 600 , 800 ]
        -Current image size: [ 600 , 800 ]
        -Camera 1 parameters after resize: [  595.718 594.982 295.232 404.435 ]
        -Sequence FPS: 30
        -Features per image: 20000
        -ORB scale factor: 1.2
        -ORB number of scales: 1
        -Initial FAST threshold: 20
        -Min FAST threshold: 7

start building cloud points

**Comment by lturing** [comment]
你缩放pcl界面试试，或者试试 https://github.com/lturing/ORB_SLAM3_ROS

**Comment by create-li** [comment]
没有效果的原因的原因是，需要先用mono_mi 跑一遍生成KeyFrameTrajectory.txt 然后再进行单目重建，可以看到点云，但是比较稀疏，看不来是原图模型形状
