### ISSUE TITLE
请教关于录制视频apk的长宽与gps的两个问题

### ISSUE THREAD

**Issue by oxyhexagen** [lturing/ORB_SLAM3_modified#5]
感谢您分享如此全面的改进。我想问下。
1.选择分辨率后800x600录到的实际分辨率是600x800，长宽发生了颠倒。
2.添加尽量与imu，相机帧同步的gps录制功能
由于不熟悉apk的开发，您能否提点下应该着重检查哪些项目文件，能修改实现上面两点吗？

**Comment by lturing** [comment]
分辨率可以参考https://github.com/lturing/ORB_SLAM3_modified/tree/main/android_app
录gps这里不支持
