### ISSUE TITLE
单目三维重建效果太差，请问什么原因

### ISSUE THREAD

**Issue by create-li** [lturing/ORB_SLAM3_modified#6]
您好，up主，基于您开源单目三维重建的项目，我复现效果如下：
一、 单目+三角化三维重建效果
1、基于开源数据集，单目+三角化实现的效果，无法看出点云重建出来场景中物体（桌子、椅子等）
![2023-08-25 20-55-44 的屏幕截图](https://github.com/lturing/ORB_SLAM3_modified/assets/9958979/365735e5-4c6c-443f-800c-982d2ca300a1)
2、基于自己手机拍摄的（单目+三角化）效果，同样是，点云比较稀疏，场景的物体无法重建。

![2023-08-25 20-58-58 的屏幕截图](https://github.com/lturing/ORB_SLAM3_modified/assets/9958979/7f1d031b-bdfc-41f5-add3-65fb96e94a87)
二、深度预测+单目三维重建效果
1、基于单目+深度预测实现的三维重建效果，场景三维重建重叠，导致像一个球，看不到场景中的物体。以下是开源数据集和自己手机拍摄数据集的效果：
![2023-08-25 21-48-04 的屏幕截图](https://github.com/lturing/ORB_SLAM3_modified/assets/9958979/db77c171-1023-40c8-a824-66497ecd311a)

![2023-08-25 21-08-43 的屏幕截图](https://github.com/lturing/ORB_SLAM3_modified/assets/9958979/2e2020d7-fadc-4faf-890c-d9b51bbb5bc8)

三、另外我使用开源数据集RGB-D稠密三维重建效果如下：
![2023-08-28 14-03-37 的屏幕截图](https://github.com/lturing/ORB_SLAM3_modified/assets/9958979/31063836-8d51-4b60-9d3e-5e89f6cb0c1c)

综上：基于您开源的单目三维重建，我复现的效果上，跟RGB-D重建的效果相差太远。请问up主，我在实现过程中的出现效果差的原因是什么？

**Comment by lturing** [comment]
1. 三角化三维重建 只是为了演示，看看中间的匹配过程，点会很稀疏；
2. 深度预测重建效果差的可能原因：a. 帧间的深度估计不连贯；b. 参数可能没设置对

这个项目当时只是为了学习用，应该存在很多问题。感谢关注

**Comment by create-li** [comment]
谢谢up 主

**Comment by LemonSoda-RPG** [comment]
你好  我或许可以解决你的部分问题  可以加一下联系方式交流一下吗

**Comment by LemonSoda-RPG** [comment]
> 你好 我或许可以解决你的部分问题 可以加一下联系方式交流一下吗

我的qq  1178010161
