### ISSUE TITLE
What is this repository?

### ISSUE THREAD

**Issue by jeremysalwen** [lturing/ORB_SLAM3_modified#8]
Hello, I am working on developing an active community supported version of ORB_SLAM at https://github.com/jeremysalwen/ORB_SLAM_COMMUNITY.

I noticed this repository, as well as a couple of other forks of ORB_SLAM on your profile.  I am wondering what the status is.  I am not Chinese speaker, so i am having difficulty reading the documentation.  Are these forks bugfixes? Improvements?  Or taking the project in a different direction?

Thank you,
Jeremy

**Comment by lturing** [comment]
just taking the project in a different direction

**Comment by jeremysalwen** [comment]
Does the fast IMU initialization work better than the original? Or does it not make much of a difference?

**Comment by slmMuc2fly** [comment]
This is for me so confusing simple words and so different at the same time

**Comment by lturing** [comment]
the fast IMU initialization in [ORB_SLAM3_FAST_IMU_INIT](https://github.com/lturing/ORB_SLAM3_FAST_IMU_INIT) is empirical, lack of theory. i test it on euroc stereo-imu dataset, the result is similar to the original orbslam3 in stereo inertial mode, while the imu initialization time decrease significantly.     
for better imu initialization method, i recommend [drt-vio-init](https://github.com/boxuLibrary/drt-vio-init) and [Stereo-NEC](https://github.com/ApdowJN/Stereo-NEC), which use Normal Epipolar Constraints to solve bg and so on

**Comment by lturing** [comment]
the repository is just my some ideas and application on orbslam3 when i study slam and orbslam, it lack mature.    
thanks for your concern.

**Comment by slmMuc2fly** [comment]
Hey!! Thanks for responding back I really appreciate it and I was completely to different direction
